#!/bin/bash
# ============================================================
# Asterisk Manager - Automated Install Script
# Tested on: Debian 12 (Bookworm) + Apache2 + PHP 8.2 + MySQL/MariaDB
# Run as root: sudo bash install.sh
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ---- Check root ----
[[ $EUID -ne 0 ]] && error "Run as root: sudo bash install.sh"

# ---- Config ----
APP_DIR="/var/www/asterisk-manager"
DB_NAME="asterisk_manager"
DB_USER="asterisk_mgr"
DB_PASS=$(openssl rand -base64 20 | tr -dc 'a-zA-Z0-9' | head -c 20)
ADMIN_PASS=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 12)
SECRET_KEY=$(openssl rand -hex 32)
ASTERISK_CONFIG="/etc/asterisk"
VHOST_NAME="asterisk-manager"

echo ""
echo "============================================================"
echo "  Asterisk Manager Installer"
echo "============================================================"
echo ""

# ---- Install dependencies ----
info "Installing PHP and required extensions..."
apt-get update -qq
apt-get install -y -qq \
    php8.2 php8.2-cli php8.2-mysql php8.2-mbstring \
    php8.2-xml php8.2-zip php8.2-curl \
    libapache2-mod-php8.2 \
    apache2 mariadb-server \
    2>/dev/null || warn "Some packages may already be installed"

success "Dependencies installed"

# ---- Enable Apache modules ----
info "Enabling Apache modules..."
a2enmod rewrite headers expires deflate php8.2 2>/dev/null || true
success "Apache modules enabled"

# ---- Copy app files ----
info "Installing application files to $APP_DIR..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "$SCRIPT_DIR" != "$APP_DIR" ]]; then
    mkdir -p "$APP_DIR"
    cp -r "$SCRIPT_DIR"/. "$APP_DIR/"
fi

# Create writable directories
mkdir -p "$APP_DIR/logs" "$APP_DIR/uploads"

# Set permissions
chown -R www-data:www-data "$APP_DIR"
chmod -R 750 "$APP_DIR"
chmod -R 770 "$APP_DIR/logs" "$APP_DIR/uploads"

# Config files need write access for www-data
if [[ -d "$ASTERISK_CONFIG" ]]; then
    chown -R root:www-data "$ASTERISK_CONFIG"
    chmod -R 664 "$ASTERISK_CONFIG"/*.conf 2>/dev/null || true
    chmod 770 "$ASTERISK_CONFIG"
    success "Asterisk config directory permissions set"
else
    warn "Asterisk config dir $ASTERISK_CONFIG not found. Set permissions manually after installing Asterisk."
fi

success "Application files installed"

# ---- Database setup ----
info "Setting up MariaDB database..."

# Start MariaDB
systemctl start mariadb 2>/dev/null || true

mysql -u root <<SQL
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
SQL

# Import schema
mysql -u root "$DB_NAME" < "$APP_DIR/install.sql"

# Set admin password hash
ADMIN_HASH=$(php -r "echo password_hash('$ADMIN_PASS', PASSWORD_BCRYPT);")
mysql -u root "$DB_NAME" <<SQL
UPDATE users SET password_hash='$ADMIN_HASH' WHERE username='admin';
SQL

success "Database created: $DB_NAME (user: $DB_USER)"

# ---- Write config.php ----
info "Writing configuration..."
cat > "$APP_DIR/config.php" <<PHP
<?php
// ============================================================
// Asterisk Manager - Configuration (auto-generated by install.sh)
// ============================================================

define('APP_VERSION', '1.0.0');
define('APP_NAME', 'Asterisk Manager');
define('APP_ROOT', __DIR__);
define('APP_URL', 'http://' . (\$_SERVER['HTTP_HOST'] ?? 'localhost') . '/asterisk-manager');

define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', '$DB_NAME');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');
define('DB_CHARSET', 'utf8mb4');

define('SESSION_NAME', 'asterisk_mgr_session');
define('SESSION_LIFETIME', 3600);

define('CSRF_TOKEN_NAME', '_csrf_token');
define('SECRET_KEY', '$SECRET_KEY');

define('ASTERISK_CONFIG_PATH', '$ASTERISK_CONFIG');
define('ASTERISK_RELOAD_CMD', '/usr/sbin/asterisk -rx');
define('LOG_PATH', APP_ROOT . '/logs');
define('UPLOAD_PATH', APP_ROOT . '/uploads');

date_default_timezone_set('Europe/Amsterdam');

error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);
ini_set('error_log', LOG_PATH . '/php_errors.log');

spl_autoload_register(function (\$class) {
    \$paths = [
        APP_ROOT . '/includes/' . \$class . '.php',
        APP_ROOT . '/controllers/' . \$class . '.php',
        APP_ROOT . '/models/' . \$class . '.php',
    ];
    foreach (\$paths as \$path) {
        if (file_exists(\$path)) { require_once \$path; return; }
    }
});

require_once APP_ROOT . '/includes/Database.php';
require_once APP_ROOT . '/includes/i18n.php';
require_once APP_ROOT . '/includes/helpers.php';
PHP

chown www-data:www-data "$APP_DIR/config.php"
chmod 640 "$APP_DIR/config.php"
success "Configuration written"

# ---- Apache VHost ----
info "Configuring Apache virtual host..."
cat > "/etc/apache2/sites-available/$VHOST_NAME.conf" <<APACHE
<VirtualHost *:80>
    ServerName asterisk-manager.local
    DocumentRoot $APP_DIR

    <Directory $APP_DIR>
        Options -Indexes -FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "\.(sql|log|bak\..*|sh|env)$">
        Require all denied
    </FilesMatch>

    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"

    ErrorLog \${APACHE_LOG_DIR}/$VHOST_NAME-error.log
    CustomLog \${APACHE_LOG_DIR}/$VHOST_NAME-access.log combined
</VirtualHost>
APACHE

a2ensite "$VHOST_NAME" 2>/dev/null || true
a2dissite 000-default 2>/dev/null || true
apache2ctl configtest && systemctl reload apache2
success "Apache configured and reloaded"

# ---- Asterisk AMI config reminder ----
info "Checking Asterisk AMI configuration..."
AMI_CONF="$ASTERISK_CONFIG/manager.conf"
if [[ -f "$AMI_CONF" ]]; then
    if ! grep -q "\[asterisk_mgr\]" "$AMI_CONF"; then
        warn "Add the following to $AMI_CONF:"
        echo ""
        echo "  [general]"
        echo "  enabled = yes"
        echo "  port = 5038"
        echo "  bindaddr = 127.0.0.1"
        echo ""
        echo "  [asterisk_mgr]"
        echo "  secret = CHANGE_THIS_AMI_SECRET"
        echo "  read = all"
        echo "  write = all"
        echo "  deny = 0.0.0.0/0.0.0.0"
        echo "  permit = 127.0.0.1/255.255.255.0"
        echo ""
    fi
else
    warn "manager.conf not found. Install Asterisk first."
fi

# ---- CDR MySQL Setup ----
info "Setting up CDR database (asteriskcdrdb)..."
mysql -u root <<SQL 2>/dev/null || true
CREATE DATABASE IF NOT EXISTS asteriskcdrdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT SELECT ON asteriskcdrdb.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
SQL
success "CDR database configured (asteriskcdrdb)"

# ---- Cron for CDR sync ----
info "Installing CDR sync cron job..."
CRON_CMD="*/5 * * * * www-data php $APP_DIR/cron/cdr_sync.php >> $APP_DIR/logs/cdr_sync.log 2>&1"
CRON_FILE="/etc/cron.d/asterisk-manager"
echo "$CRON_CMD" > "$CRON_FILE"
chmod 644 "$CRON_FILE"

mkdir -p "$APP_DIR/cron"
cat > "$APP_DIR/cron/cdr_sync.php" <<'CRONPHP'
<?php
// CDR Auto-sync cron job
define('APP_ROOT', dirname(__DIR__));
require_once APP_ROOT . '/config.php';
require_once APP_ROOT . '/includes/AsteriskAMI.php';
require_once APP_ROOT . '/controllers/CDRController.php';

$cdr = new CDRController();
CDRController::applyRatesToCDR();
echo date('Y-m-d H:i:s') . " CDR costs applied\n";
CRONPHP

chown www-data:www-data "$APP_DIR/cron/cdr_sync.php"
success "CDR sync cron installed (every 5 minutes)"

# ---- Summary ----
echo ""
echo "============================================================"
echo -e "  ${GREEN}Installation Complete!${NC}"
echo "============================================================"
echo ""
echo -e "  URL:           ${CYAN}http://$(hostname -I | awk '{print $1}')/${NC}"
echo -e "  Admin user:    ${CYAN}admin${NC}"
echo -e "  Admin pass:    ${YELLOW}$ADMIN_PASS${NC}"
echo ""
echo -e "  Database:      ${CYAN}$DB_NAME${NC}"
echo -e "  DB user:       ${CYAN}$DB_USER${NC}"
echo -e "  DB password:   ${YELLOW}$DB_PASS${NC}"
echo ""
echo "  NEXT STEPS:"
echo "  1. Visit the URL above and login"
echo "  2. Go to Settings → Asterisk → enter your AMI credentials"
echo "  3. Add the [asterisk_mgr] block to /etc/asterisk/manager.conf"
echo "  4. Reload Asterisk: asterisk -rx 'core reload'"
echo "  5. Add trunks, extensions, routes, and ring groups"
echo ""
echo -e "  ${RED}Save these credentials now — they won't be shown again!${NC}"
echo "============================================================"
echo ""
