<?php
// ============================================================
// AsteriskConfig - Generates Asterisk config files
// Asterisk 22 / PJSIP - Inbound/Outbound split
// ============================================================

class AsteriskConfig
{
    private string $configPath;

    public function __construct(string $configPath = '/etc/asterisk')
    {
        $this->configPath = rtrim($configPath, '/');
    }

    public static function fromSettings(): self
    {
        return new self(Database::getSetting('asterisk_config_path', '/etc/asterisk'));
    }

    private function writeFile(string $filename, string $content): bool
    {
        $path = $this->configPath . '/' . $filename;
        if (file_exists($path)) {
            copy($path, $path . '.bak.' . date('YmdHis'));
        }
        $result = file_put_contents($path, $content);
        if ($result === false) {
            logError("Failed to write: $path");
            return false;
        }
        chmod($path, 0640);
        return true;
    }

    private function header(string $title): string
    {
        $line = str_repeat(';', 60);
        $date = date('Y-m-d H:i:s');
        return ";$line\n; $title\n; Generated by Asterisk Manager on $date\n; DO NOT EDIT MANUALLY\n;$line\n\n";
    }

    // ============================================================
    // PJSIP
    // ============================================================

    public function generatePJSIP(): bool
    {
        $trunks     = Database::fetchAll("SELECT * FROM trunks WHERE enabled=1 AND type='pjsip'");
        $extensions = Database::fetchAll("SELECT * FROM extensions WHERE enabled=1");

        $externalHost = Database::getSetting('asterisk_external_host', '');
        $localNets    = Database::getSetting('asterisk_local_nets', '192.168.0.0/16,172.16.0.0/12,10.0.0.0/8');

        $out  = $this->header('PJSIP Configuration');

        // Transport UDP
        $out .= "[transport-udp]\n";
        $out .= "type=transport\n";
        $out .= "protocol=udp\n";
        $out .= "bind=0.0.0.0\n";
        if (!empty($externalHost)) {
            $out .= "external_media_address=" . $externalHost . "\n";
            $out .= "external_signaling_address=" . $externalHost . "\n";
            foreach (explode(',', $localNets) as $net) {
                $net = trim($net);
                if ($net) {
                    $out .= "local_net=" . $net . "\n";
                }
            }
        }
        $out .= "\n";

        // Transport TCP
        $out .= "[transport-tcp]\n";
        $out .= "type=transport\n";
        $out .= "protocol=tcp\n";
        $out .= "bind=0.0.0.0\n\n";

        // Extensions
        foreach ($extensions as $ext) {
            $out .= $this->pjsipEndpoint($ext);
        }

        // Trunks
        foreach ($trunks as $trunk) {
            $type = $trunk['trunk_type'] ?? 'provider';
            if ($type === 'pbx') {
                $out .= $this->pjsipTrunkPBX($trunk);
            } else {
                $out .= $this->pjsipTrunk($trunk);
            }
        }

        return $this->writeFile('pjsip.conf', $out);
    }

    private function pjsipEndpoint(array $ext): string
    {
        $exten     = $ext['extension'];
        $secret    = $ext['secret'] ?? '';
        $context   = $ext['context'] ?? 'from-internal';
        $cidName   = $ext['callerid_name'] ?? '';
        $cidNum    = $ext['callerid_number'] ?? '';
        $maxCon    = (int)($ext['max_contacts'] ?? 1);
        $dtmf      = $ext['dtmf_mode'] ?? 'rfc4733';
        $recording = $ext['call_recording'] ?? 'never';
        $vmEnabled = !empty($ext['voicemail_enabled']);
        $codecs    = $ext['codecs'] ?? 'ulaw,alaw,g722';
        $out       = '';

        // Asterisk 22: alle secties hebben dezelfde naam, type= maakt het onderscheid
        $out .= '[' . $exten . "]\n";
        $out .= "type=auth\n";
        $out .= "auth_type=userpass\n";
        $out .= 'username=' . $exten . "\n";
        $out .= 'password=' . $secret . "\n\n";

        $out .= '[' . $exten . "]\n";
        $out .= "type=aor\n";
        $out .= 'max_contacts=' . $maxCon . "\n";
        $out .= "remove_existing=yes\n";
        $out .= "qualify_frequency=30\n";
        if ($vmEnabled) {
            $out .= 'mailboxes=' . $exten . "@default\n";
        }
        $out .= "\n";

        $out .= '[' . $exten . "]\n";
        $out .= "type=endpoint\n";
        $out .= 'context=' . $context . "\n";
        $out .= 'auth=' . $exten . "\n";
        $out .= 'aors=' . $exten . "\n";
        $out .= 'callerid=' . $cidName . ' <' . $cidNum . ">\n";
        $out .= 'allow=' . $codecs . "\n";
        $out .= 'dtmf_mode=' . $dtmf . "\n";
        $out .= "direct_media=no\n";
        $out .= "ice_support=no\n";
        // ACL - standaard alleen intern netwerk
        $out .= "deny=0.0.0.0/0.0.0.0\n";
        $out .= "permit=172.16.0.0/12\n";
        $out .= "permit=10.0.0.0/8\n";
        $out .= "permit=192.168.0.0/16\n";
        if (!empty($ext['allowed_ips'])) {
            foreach (array_filter(array_map('trim', explode(",", $ext['allowed_ips']))) as $allowedIp) {
                $out .= "permit=" . $allowedIp . "\n";
            }
        }
        // Max 2 gelijktijdige gesprekken per extensie
        $out .= "max_audio_streams=2\n";
        if ($recording === 'always') {
            $out .= "record_calls=yes\n";
        }
        $out .= "\n";

        return $out;
    }

    private function pjsipTrunk(array $trunk): string
    {
        $name       = $trunk['name'];
        $host       = $trunk['host'];
        $port       = $trunk['port'] ?? 5060;
        $username   = $trunk['username'];
        $password   = $trunk['password'];
        $context    = $trunk['context'] ?? 'from-trunk';
        $codecs     = $trunk['codecs'] ?? 'ulaw,alaw,g722';
        $outboundCid = $trunk['outbound_cid'] ?? '';
        $resolvedIp = gethostbyname($host);
        $out        = '';

        // ---- Uitgaand: met authenticatie ----
        $out .= "; === Trunk: " . $name . " (outbound) ===\n";

        $out .= "[reg-" . $name . "]\n";
        $out .= "type=registration\n";
        $out .= "transport=transport-udp\n";
        $out .= "outbound_auth=" . $name . "-auth\n";
        $out .= "server_uri=sip:" . $host . ":" . $port . "\n";
        $out .= "client_uri=sip:" . $username . "@" . $host . ":" . $port . "\n";
        $out .= "contact_user=" . $username . "\n";
        $out .= "retry_interval=60\n";
        $out .= "expiration=3600\n\n";

        $out .= "[" . $name . "-auth]\n";
        $out .= "type=auth\n";
        $out .= "auth_type=userpass\n";
        $out .= "username=" . $username . "\n";
        $out .= "password=" . $password . "\n\n";

        $out .= "[" . $name . "-aor]\n";
        $out .= "type=aor\n";
        $out .= "contact=sip:" . $username . "@" . $host . ":" . $port . "\n\n";

        $out .= "[" . $name . "]\n";
        $out .= "type=endpoint\n";
        $out .= "transport=transport-udp\n";
        $out .= "context=" . $context . "\n";
        $out .= "aors=" . $name . "-aor\n";
        $out .= "auth=" . $name . "-auth\n";
        $out .= "outbound_auth=" . $name . "-auth\n";
        $out .= "allow=" . $codecs . "\n";
        // from_user weggelaten zodat Asterisk het CallerID van de extensie gebruikt
        $out .= "from_domain=" . $host . "\n";
        $out .= "direct_media=no\n";
        $out .= "rtp_symmetric=yes\n";
        $out .= "force_rport=yes\n";
        $out .= "rewrite_contact=yes\n";
        if (!empty($outboundCid)) {
            $out .= "callerid=" . $outboundCid . " <" . $outboundCid . ">\n";
        }
        $out .= "send_pai=yes\n";
        $out .= "send_rpid=yes\n";
        $out .= "\n";

        // ---- Inkomend: geen authenticatie, IP-gebaseerd ----
        $out .= "; === Trunk: " . $name . " (inbound) ===\n";

        $out .= "[" . $name . "-inbound]\n";
        $out .= "type=endpoint\n";
        $out .= "transport=transport-udp\n";
        $out .= "context=" . $context . "\n";
        $out .= "allow=" . $codecs . "\n";
        $out .= "direct_media=no\n";
        $out .= "rtp_symmetric=yes\n";
        $out .= "force_rport=yes\n";
        $out .= "rewrite_contact=yes\n";
        $out .= "trust_id_inbound=yes\n\n";

        $out .= "[" . $name . "-inbound]\n";
        $out .= "type=aor\n";
        $out .= "contact=sip:" . $host . ":" . $port . "\n\n";

        $out .= "[" . $name . "-inbound]\n";
        $out .= "type=identify\n";
        $out .= "endpoint=" . $name . "-inbound\n";
        $out .= "match=" . $host . "\n";
        if (!empty($resolvedIp) && $resolvedIp !== $host) {
            $out .= "match=" . $resolvedIp . "\n";
        }
        $out .= "\n";

        return $out;
    }

    private function pjsipTrunkPBX(array $trunk): string
    {
        $name       = $trunk['name'];
        $host       = $trunk['host'];
        $port       = $trunk['port'] ?? 5060;
        $username   = $trunk['username'];
        $password   = $trunk['password'];
        $context    = $trunk['context'] ?? 'from-internal';
        $codecs     = $trunk['codecs'] ?? 'ulaw,alaw,g722';
        $resolvedIp = gethostbyname($host);
        $out        = '';

        $out .= "; === PBX Trunk: " . $name . " (3CX/PBX) ===
";

        // Auth sectie
        $out .= "[" . $name . "-auth]
";
        $out .= "type=auth
";
        $out .= "auth_type=userpass
";
        $out .= "username=" . $username . "
";
        $out .= "password=" . $password . "

";

        // AOR sectie
        $out .= "[" . $name . "-aor]
";
        $out .= "type=aor
";
        $out .= "contact=sip:" . $host . ":" . $port . "
";
        $out .= "qualify_frequency=30

";

        // Outbound endpoint
        $out .= "[" . $name . "]
";
        $out .= "type=endpoint
";
        $out .= "transport=transport-udp
";
        $out .= "context=" . $context . "
";
        $out .= "aors=" . $name . "-aor
";
        $out .= "auth=" . $name . "-auth
";
        $out .= "outbound_auth=" . $name . "-auth
";
        $out .= "allow=" . $codecs . "
";
        $out .= "from_domain=" . $host . "
";
        $out .= "direct_media=no
";
        $out .= "rtp_symmetric=yes
";
        $out .= "force_rport=yes
";
        $out .= "rewrite_contact=yes
";
        $out .= "trust_id_inbound=yes
";
        $out .= "send_pai=yes
";
        $out .= "send_rpid=yes

";

        // Inbound endpoint - IP gebaseerd, geen auth
        $out .= "[" . $name . "-inbound]
";
        $out .= "type=endpoint
";
        $out .= "transport=transport-udp
";
        $out .= "context=" . $context . "
";
        $out .= "allow=" . $codecs . "
";
        $out .= "direct_media=no
";
        $out .= "rtp_symmetric=yes
";
        $out .= "force_rport=yes
";
        $out .= "rewrite_contact=yes
";
        $out .= "trust_id_inbound=yes

";

        $out .= "[" . $name . "-inbound]
";
        $out .= "type=aor
";
        $out .= "contact=sip:" . $host . ":" . $port . "

";

        // Identify op IP
        $out .= "[" . $name . "-inbound]
";
        $out .= "type=identify
";
        $out .= "endpoint=" . $name . "-inbound
";
        $out .= "match=" . $host . "
";
        if (!empty($resolvedIp) && $resolvedIp !== $host) {
            $out .= "match=" . $resolvedIp . "
";
        }
        $out .= "
";

        return $out;
    }

    // ============================================================
    // QUEUES
    // ============================================================

    public function generateQueues(): bool
    {
        $queues = Database::fetchAll("SELECT * FROM queues WHERE enabled=1");
        $out    = $this->header('Queues Configuration');
        $out   .= "[general]\n\n";
        foreach ($queues as $queue) {
            $members = Database::fetchAll(
                "SELECT * FROM queue_members WHERE queue_id=? ORDER BY penalty",
                [$queue['id']]
            );
            $out .= $this->queueBlock($queue, $members);
        }
        return $this->writeFile('queues.conf', $out);
    }

    private function queueBlock(array $queue, array $members): string
    {
        $out  = '[' . $queue['name'] . "]\n";
        $out .= 'strategy=' . $queue['strategy'] . "\n";
        $out .= 'timeout=' . $queue['timeout'] . "\n";
        $out .= 'wrapuptime=' . $queue['wrapup_time'] . "\n";
        $out .= 'maxlen=' . $queue['max_callers'] . "\n";
        $out .= 'announce-holdtime=' . $queue['announce_hold_time'] . "\n";
        $out .= 'announce-position=' . $queue['announce_position'] . "\n";
        $out .= 'announce-frequency=' . $queue['announce_frequency'] . "\n";
        $out .= 'musicclass=' . $queue['music_on_hold'] . "\n";
        if (!empty($queue['join_announcement'])) {
            $out .= 'announce=' . $queue['join_announcement'] . "\n";
        }
        foreach ($members as $m) {
            $out .= 'member => PJSIP/' . $m['extension'] . ',penalty=' . ($m['penalty'] ?? 0) . "\n";
        }
        $out .= "\n";
        return $out;
    }

    // ============================================================
    // DIALPLAN (extensions.conf)
    // ============================================================

    public function generateDialplan(): bool
    {
        $out  = $this->header('Extensions (Dialplan)');
        $out .= $this->generateFromInternal();
        $out .= $this->generateFromTrunk();
        $out .= "[from-internal-custom]\n; Add custom rules here\n\n";
        $out .= "[from-trunk-custom]\n; Add custom rules here\n\n";
        $out .= $this->generateCustomContexts();
        return $this->writeFile('extensions.conf', $out);
    }

    private function generateFromInternal(): string
    {
        $extensions     = Database::fetchAll("SELECT * FROM extensions WHERE enabled=1");
        $ringGroups     = Database::fetchAll("SELECT * FROM ring_groups WHERE enabled=1");
        $queues         = Database::fetchAll("SELECT * FROM queues WHERE enabled=1");
        $outboundRoutes = Database::fetchAll("SELECT * FROM outbound_routes WHERE enabled=1 ORDER BY priority DESC");

        $out  = "[from-internal]\n";
        $out .= "include => from-internal-custom\n\n";

        // Extensies
        foreach ($extensions as $ext) {
            $exten    = $ext['extension'];
            $cidName  = $ext['callerid_name'] ?? '';
            $vmOn     = !empty($ext['voicemail_enabled']);
            $cfAlways = trim($ext['cf_always'] ?? '');
            $cfBusy   = trim($ext['cf_busy'] ?? '');
            $cfNoAns  = trim($ext['cf_noanswer'] ?? '');
            $cfVm     = !empty($ext['cf_voicemail']);
            $ringTime = (int)($ext['ring_time'] ?? 20);

            $out .= 'exten => ' . $exten . ",1,NoOp(Call to extension " . $exten . ")\n";
            $out .= ' same => n,Set(CALLERID(name)=' . $cidName . ")\n";

            // Altijd doorschakelen
            if (!empty($cfAlways)) {
                $out .= ' same => n,Dial(Local/' . $cfAlways . "@from-internal,60,tT)\n";
                $out .= " same => n,Hangup()\n\n";
                continue;
            }

            // Normaal bellen met busy/noanswer handling
            $dialOpts = 'tTr';
            if (!empty($cfBusy)) $dialOpts .= 'j'; // j = jump on busy
            $out .= ' same => n,Dial(PJSIP/' . $exten . ',' . $ringTime . ',' . $dialOpts . ")\n";

            // Bij bezet
            if (!empty($cfBusy)) {
                $out .= ' same => n(busy),Dial(Local/' . $cfBusy . "@from-internal,60,tT)\n";
            }

            // Bij geen antwoord - extern of voicemail
            if (!empty($cfNoAns)) {
                $out .= ' same => n,Dial(Local/' . $cfNoAns . "@from-internal,60,tT)\n";
            } elseif ($cfVm && $vmOn) {
                $out .= ' same => n,VoiceMail(' . $exten . "@default,u)\n";
            } elseif ($vmOn) {
                $out .= ' same => n,VoiceMail(' . $exten . "@default,u)\n";
            }

            $out .= " same => n,Hangup()\n\n";
        }

        // Ring Groups
        foreach ($ringGroups as $rg) {
            $members   = Database::fetchAll(
                "SELECT * FROM ring_group_members WHERE ring_group_id=? ORDER BY order_num",
                [$rg['id']]
            );
            $dialParts = array_map(fn($m) => 'PJSIP/' . $m['extension'], $members);
            $dialStr   = implode('&', $dialParts);
            $cidPrefix = $rg['caller_id_prefix'] ?? '';
            $out .= 'exten => ' . $rg['number'] . ",1,NoOp(Ring Group: " . $rg['name'] . ")\n";
            if ($cidPrefix) {
                $out .= ' same => n,Set(CALLERID(name)=' . $cidPrefix . '${CALLERID(name)}' . ")\n";
            }
            $out .= ' same => n,Dial(' . $dialStr . ',' . $rg['ring_time'] . ",tTr)\n";
            $out .= $this->destinationLine($rg['destination_type'], $rg['destination']);
            $out .= " same => n,Hangup()\n\n";
        }

        // Queues
        foreach ($queues as $q) {
            $out .= 'exten => ' . $q['number'] . ",1,NoOp(Queue: " . $q['name'] . ")\n";
            if (!empty($q['join_announcement'])) {
                $out .= ' same => n,Playback(' . $q['join_announcement'] . ")\n";
            }
            $out .= ' same => n,Queue(' . $q['name'] . ",tT)\n";
            $out .= $this->destinationLine($q['timeout_destination_type'], $q['timeout_destination']);
            $out .= " same => n,Hangup()\n\n";
        }

        // Voicemail toegang
        $out .= "exten => *98,1,NoOp(Voicemail Access)\n";
        $out .= ' same => n,VoiceMailMain(${CALLERID(num)}@default)' . "\n";
        $out .= " same => n,Hangup()\n\n";

        // Uitgaande routes
        foreach ($outboundRoutes as $route) {
            $patterns = Database::fetchAll(
                "SELECT * FROM outbound_route_dial_patterns WHERE route_id=?",
                [$route['id']]
            );
            $trunks = Database::fetchAll(
                "SELECT t.* FROM trunks t
                 JOIN outbound_route_trunks ort ON t.id=ort.trunk_id
                 WHERE ort.route_id=? AND t.enabled=1
                 ORDER BY ort.order_num",
                [$route['id']]
            );
            if (empty($trunks)) continue;
            $trunkName = $trunks[0]['name'];

            foreach ($patterns as $p) {
                $match    = trim($p['match_pattern']);
                $prepend  = trim($p['prepend'] ?? '');
                $prefix   = trim($p['prefix'] ?? '');
                $stripLen = strlen($prefix);
                if (empty($match)) continue;

                $out .= 'exten => ' . $match . ',1,NoOp(Outbound: ' . $route['name'] . ")\n";
                if ($prepend !== '' || $prefix !== '') {
                    $extenVar = '${EXTEN:' . $stripLen . '}';
                    $out .= ' same => n,Set(OUTNUM=' . $prepend . $extenVar . ")\n";
                    $out .= ' same => n,Dial(PJSIP/${OUTNUM}@' . $trunkName . ",60,tT)\n";
                } else {
                    $out .= ' same => n,Dial(PJSIP/${EXTEN}@' . $trunkName . ",60,tT)\n";
                }
                $out .= " same => n,Hangup()\n\n";
            }
        }

        return $out;
    }

    private function generateFromTrunk(): string
    {
        $routes = Database::fetchAll("SELECT * FROM inbound_routes WHERE enabled=1 ORDER BY priority DESC");
        $out    = "[from-trunk]\n";
        $out   .= "include => from-trunk-custom\n\n";

        foreach ($routes as $route) {
            $did  = !empty($route['did']) ? $route['did'] : 's';
            $out .= 'exten => ' . $did . ",1,NoOp(Inbound DID: " . $did . ")\n";
            $out .= " same => n,Answer()\n";
            $out .= $this->destinationLine($route['destination_type'], $route['destination']);
            $out .= " same => n,Hangup()\n\n";
        }

        // Catch-all
        $out .= "exten => _.,1,NoOp(Unknown inbound)\n";
        $out .= " same => n,Hangup(21)\n\n";

        return $out;
    }

    private function destinationLine(string $type, string $destination): string
    {
        $dest = $destination;
        return match ($type) {
            'extension'    => " same => n,Goto(from-internal," . $dest . ",1)\n",
            'queue'        => " same => n,Queue(" . $dest . ",tT)\n",
            'ring_group'   => " same => n,Goto(from-internal," . $dest . ",1)\n",
            'voicemail'    => " same => n,VoiceMail(" . $dest . "@default,u)\n",
            'external'     => " same => n,Dial(Local/" . $dest . "@from-internal,60,tT)\n",
            'announcement' => " same => n,Playback(" . $dest . ")\n same => n,Hangup()\n",
            default        => " same => n,Hangup()\n",
        };
    }

    private function generateCustomContexts(): string
    {
        $contexts = Database::fetchAll("SELECT * FROM dialplan_contexts");
        $out      = '';
        foreach ($contexts as $ctx) {
            $entries = Database::fetchAll(
                "SELECT * FROM dialplan_entries WHERE context_id=? ORDER BY extension, priority",
                [$ctx['id']]
            );
            if (empty($entries)) continue;
            $out .= '[' . $ctx['name'] . "]\n";
            if ($ctx['description']) {
                $out .= '; ' . $ctx['description'] . "\n";
            }
            foreach ($entries as $e) {
                $out .= 'exten => ' . $e['extension'] . ',' . $e['priority'] . ',';
                $out .= $e['application'] . '(' . ($e['app_data'] ?? '') . ")\n";
            }
            $out .= "\n";
        }
        return $out;
    }

    // ============================================================
    // RELOAD
    // ============================================================

    public function reload(?string $module = null): bool
    {
        $ami = AsteriskAMI::fromSettings();
        if (!$ami->connect()) {
            $cmd = '/usr/sbin/asterisk -rx "core reload"';
            exec($cmd . ' 2>&1', $output, $code);
            return $code === 0;
        }
        $result = $ami->reload($module ?? '');
        $ami->disconnect();
        return $result;
    }
}
