<?php
// ============================================================
// GigasetProvisioning - Genereert Gigaset XML config bestanden
// Ondersteunt: N300, N300A, N510, N510 IP PRO
// ============================================================

class GigasetProvisioning
{
    private static array $timezoneMap = [
        'Europe/Amsterdam' => ['CET-1CEST-2,M3.5.0/2,M10.5.0/3', '+01:00', 'Europe/Amsterdam'],
        'Europe/London'    => ['GMT0BST-1,M3.5.0/1,M10.5.0/2',   '+00:00', 'Europe/London'],
        'Europe/Berlin'    => ['CET-1CEST-2,M3.5.0/2,M10.5.0/3', '+01:00', 'Europe/Berlin'],
        'Europe/Paris'     => ['CET-1CEST-2,M3.5.0/2,M10.5.0/3', '+01:00', 'Europe/Paris'],
        'UTC'              => ['UTC0',                              '+00:00', 'UTC'],
    ];

    public static function generate(array $phone): string
    {
        // Haal alle extensies op die aan deze DECT base gekoppeld zijn
        $extensions = self::getExtensions($phone);
        if (empty($extensions)) return '';

        $tz        = $phone['timezone'] ?? 'Europe/Amsterdam';
        $tzData    = self::$timezoneMap[$tz] ?? self::$timezoneMap['Europe/Amsterdam'];
        $sipServer = Database::getSetting('asterisk_external_host', '');
        if (empty($sipServer)) {
            $sipServer = Database::getSetting('asterisk_host', '127.0.0.1');
        }
        $ntpServer   = $phone['ntp_server'] ?? Database::getSetting('provision_ntp_server', 'pool.ntp.org');
        $adminPass   = $phone['admin_password'] ?? Database::getSetting('provision_admin_pass', 'admin');

        $xml  = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
        $xml .= '<!-- Gigaset Provisioning - Generated by Asterisk Manager ' . date('Y-m-d H:i:s') . ' -->' . "\n";
        $xml .= '<provisioning version="1">' . "\n";

        // ---- Systeem instellingen ----
        $xml .= '  <system-settings>' . "\n";
        $xml .= '    <admin-password>' . htmlspecialchars($adminPass) . '</admin-password>' . "\n";
        $xml .= '    <user-password>' . htmlspecialchars($adminPass) . '</user-password>' . "\n";
        $xml .= '  </system-settings>' . "\n\n";

        // ---- Netwerk / NTP ----
        $xml .= '  <network-settings>' . "\n";
        $xml .= '    <ntp-server>' . htmlspecialchars($ntpServer) . '</ntp-server>' . "\n";
        $xml .= '    <ntp-refresh-interval>3600</ntp-refresh-interval>' . "\n";
        $xml .= '  </network-settings>' . "\n\n";

        // ---- Datum & Tijd ----
        $xml .= '  <datetime-settings>' . "\n";
        $xml .= '    <timezone>' . htmlspecialchars($tzData[2]) . '</timezone>' . "\n";
        $xml .= '    <dst-setting>auto</dst-setting>' . "\n";
        $xml .= '    <time-format>24hour</time-format>' . "\n";
        $xml .= '    <date-format>dd.mm.yyyy</date-format>' . "\n";
        $xml .= '  </datetime-settings>' . "\n\n";

        // ---- VoIP providers (SIP accounts) ----
        $xml .= '  <voip-settings>' . "\n";

        foreach ($extensions as $i => $ext) {
            $providerNum = $i + 1;
            $xml .= '    <provider id="' . $providerNum . '">' . "\n";
            $xml .= '      <name>' . htmlspecialchars($ext['full_name'] ?: $ext['extension']) . '</name>' . "\n";
            $xml .= '      <domain>' . htmlspecialchars($sipServer) . '</domain>' . "\n";
            $xml .= '      <proxy>' . htmlspecialchars($sipServer) . '</proxy>' . "\n";
            $xml .= '      <proxy-port>5060</proxy-port>' . "\n";
            $xml .= '      <registration-server>' . htmlspecialchars($sipServer) . '</registration-server>' . "\n";
            $xml .= '      <registration-port>5060</registration-port>' . "\n";
            $xml .= '      <username>' . htmlspecialchars($ext['extension']) . '</username>' . "\n";
            $xml .= '      <auth-username>' . htmlspecialchars($ext['extension']) . '</auth-username>' . "\n";
            $xml .= '      <password>' . htmlspecialchars($ext['secret']) . '</password>' . "\n";
            $xml .= '      <display-name>' . htmlspecialchars($ext['full_name'] ?: $ext['extension']) . '</display-name>' . "\n";
            $xml .= '      <registration-refresh>120</registration-refresh>' . "\n";
            $xml .= '      <dtmf-mode>rfc2833</dtmf-mode>' . "\n";
            $xml .= '      <codec-1>G711a</codec-1>' . "\n";
            $xml .= '      <codec-2>G711u</codec-2>' . "\n";
            $xml .= '      <codec-3>G722</codec-3>' . "\n";
            $xml .= '      <srtp>off</srtp>' . "\n";
            $xml .= '    </provider>' . "\n";
        }

        $xml .= '  </voip-settings>' . "\n\n";

        // ---- Handsets (een per extensie) ----
        $xml .= '  <handset-settings>' . "\n";

        foreach ($extensions as $i => $ext) {
            $handsetNum  = $i + 1;
            $providerNum = $i + 1;
            $xml .= '    <handset id="' . $handsetNum . '">' . "\n";
            $xml .= '      <name>' . htmlspecialchars($ext['full_name'] ?: ('Handset ' . $handsetNum)) . '</name>' . "\n";
            $xml .= '      <voip-provider-id>' . $providerNum . '</voip-provider-id>' . "\n";
            $xml .= '      <outgoing-provider>' . $providerNum . '</outgoing-provider>' . "\n";
            $xml .= '    </handset>' . "\n";
        }

        $xml .= '  </handset-settings>' . "\n\n";

        // ---- Auto provisioning ----
        $baseUrl = rtrim(Database::getSetting('provision_base_url', ''), '/');
        if (!empty($baseUrl)) {
            $mac = strtolower(str_replace([':', '-'], '', $phone['mac_address']));
            $xml .= '  <autoprovisioning>' . "\n";
            $xml .= '    <server-url>' . htmlspecialchars($baseUrl . '/' . $mac . '.xml') . '</server-url>' . "\n";
            $xml .= '    <check-interval>1440</check-interval>' . "\n";
            $xml .= '  </autoprovisioning>' . "\n\n";
        }

        $xml .= '</provisioning>' . "\n";

        return $xml;
    }

    private static function getExtensions(array $phone): array
    {
        // Haal hoofd extensie op
        $mainExt = Database::fetchOne(
            "SELECT * FROM extensions WHERE id=?",
            [$phone['extension_id']]
        );
        if (!$mainExt) return [];

        $extensions = [$mainExt];

        // Haal extra extensies op als die gekoppeld zijn
        if (!empty($phone['extra_extensions'])) {
            $extraIds = array_filter(array_map('intval', explode(',', $phone['extra_extensions'])));
            foreach ($extraIds as $extId) {
                $ext = Database::fetchOne("SELECT * FROM extensions WHERE id=? AND enabled=1", [$extId]);
                if ($ext) $extensions[] = $ext;
            }
        }

        return $extensions;
    }

    public static function getMacFilename(string $mac): string
    {
        return strtolower(str_replace([':', '-', ' '], '', $mac)) . '.xml';
    }

    public static function writeConfigFile(array $phone): bool
    {
        $provPath = Database::getSetting('provision_tftp_path', APP_ROOT . '/provision');
        if (!is_dir($provPath)) {
            @mkdir($provPath, 0755, true);
        }

        $content  = self::generate($phone);
        $filename = $provPath . '/' . self::getMacFilename($phone['mac_address']);
        $result   = file_put_contents($filename, $content);

        if ($result !== false) {
            @chmod($filename, 0644);
            Database::update('provision_phones', [
                'last_provision' => date('Y-m-d H:i:s')
            ], 'id=?', [$phone['id']]);
            return true;
        }
        return false;
    }

    public static function getModels(): array
    {
        return [
            'N300'         => 'Gigaset N300',
            'N300A'        => 'Gigaset N300A (met antwoordapparaat)',
            'N510'         => 'Gigaset N510 IP PRO',
            'N720'         => 'Gigaset N720 IP PRO (multicell)',
            'N870'         => 'Gigaset N870 IP PRO (multicell)',
        ];
    }
}
