<?php
// ============================================================
// YealinkProvisioning - Genereert Yealink config bestanden
// Gebaseerd op officieel 3CX Yealink template formaat
// ============================================================

class YealinkProvisioning
{
    private static array $timezoneMap = [
        'Europe/Amsterdam' => ['+1', 'Netherlands(Amsterdam)'],
        'Europe/London'    => ['0',  'United Kingdom(London)'],
        'Europe/Berlin'    => ['+1', 'Germany(Berlin)'],
        'Europe/Paris'     => ['+1', 'France(Paris)'],
        'Europe/Brussels'  => ['+1', 'Belgium(Brussels)'],
        'Europe/Rome'      => ['+1', 'Italy(Rome)'],
        'Europe/Madrid'    => ['+1', 'Spain(Madrid)'],
        'UTC'              => ['0',  'GMT'],
        'America/New_York' => ['-5', 'United States-Eastern Time'],
        'America/Chicago'  => ['-6', 'United States-Central Time'],
        'America/Los_Angeles' => ['-8', 'United States-Pacific Time'],
    ];

    private static array $keyTypes = [
        'blf'        => 16,
        'speed_dial' => 13,
        'line'       => 15,
        'dtmf'       => 12,
        'conference' => 9,
        'forward'    => 7,
        'transfer'   => 6,
        'hold'       => 5,
        'dnd'        => 4,
    ];

    public static function generate(array $phone): string
    {
        $ext = Database::fetchOne(
            "SELECT * FROM extensions WHERE id=?",
            [$phone['extension_id']]
        );
        if (!$ext) return '';

        $blfKeys = Database::fetchAll(
            "SELECT pk.*, e.extension as ext_number, e.full_name as ext_name
             FROM provision_blf_keys pk
             LEFT JOIN extensions e ON pk.extension_id = e.id
             WHERE pk.phone_id = ?
             ORDER BY pk.key_number",
            [$phone['id']]
        );

        $tz          = $phone['timezone'] ?? 'Europe/Amsterdam';
        $tzData      = self::$timezoneMap[$tz] ?? self::$timezoneMap['Europe/Amsterdam'];
        $sipServer   = Database::getSetting('asterisk_external_host', '');
        if (empty($sipServer)) {
            $sipServer = Database::getSetting('asterisk_host', '127.0.0.1');
        }
        $sipPort     = '5060';
        $ntpServer   = $phone['ntp_server'] ?? Database::getSetting('provision_ntp_server', 'pool.ntp.org');
        $adminPass   = $phone['admin_password'] ?? Database::getSetting('provision_admin_pass', 'admin');
        $language    = $phone['language'] ?? 'Dutch';
        $displayName = $phone['display_name'] ?: ($ext['full_name'] ?? $ext['extension']);
        $baseUrl     = rtrim(Database::getSetting('provision_base_url', ''), '/');
        $extension   = $ext['extension'];
        $secret      = $ext['secret'];
        $codecs      = $ext['codecs'] ?? 'ulaw,alaw,g722';

        $langMap = [
            'Dutch'    => ['Dutch', 'Dutch'],
            'English'  => ['English', 'English'],
            'German'   => ['German', 'German'],
            'French'   => ['French', 'French'],
            'Spanish'  => ['Spanish', 'Spanish'],
            'Italian'  => ['Italian', 'Italian'],
        ];
        [$langWeb, $langLcd] = $langMap[$language] ?? ['English', 'English'];

        $cfg  = "#!version:1.0.0.1\n";
        $cfg .= "## Generated by Asterisk Manager - " . date('Y-m-d H:i:s') . "\n";
        $cfg .= "## Extension: $extension - " . ($ext['full_name'] ?? '') . "\n";
        $cfg .= "## MAC: " . $phone['mac_address'] . "\n\n";
        $cfg .= "overwrite_mode = 1\n\n";

        // Auto Provisioning
        $cfg .= "###################################################\n";
        $cfg .= "## Auto Provisioning\n";
        $cfg .= "###################################################\n";
        $cfg .= "auto_provision.mode = 1\n";
        $cfg .= "auto_provision.repeat.enable = 1\n";
        $cfg .= "auto_provision.repeat.minutes = 1440\n";
        $cfg .= "auto_provision.reboot_force.enable = 0\n";
        $cfg .= "auto_provision.pnp_enable = 1\n";
        $cfg .= "auto_provision.custom.sync = 0\n";
        $cfg .= "auto_provision.custom.protect = 0\n";
        if (!empty($baseUrl)) {
            $mac = strtolower(str_replace([':', '-'], '', $phone['mac_address']));
            $cfg .= "auto_provision.server.url = " . $baseUrl . "/" . $mac . ".cfg\n";
        }
        $cfg .= "auto_provision.server.username = \n";
        $cfg .= "auto_provision.server.password = \n\n";

        // Security
        $cfg .= "###################################################\n";
        $cfg .= "## Security\n";
        $cfg .= "###################################################\n";
        $cfg .= "security.trust_certificates = 0\n";
        $cfg .= "security.cn_validation = 0\n";
        $cfg .= "security.default_ssl_method = 5\n";
        $cfg .= "security.user_name.admin = admin\n";
        $cfg .= "security.user_password = admin:" . $adminPass . "\n";
        $cfg .= "security.user_name.user = user\n";
        $cfg .= "security.user_password = user:" . $adminPass . "\n\n";

        // Tijd & Datum
        $cfg .= "###################################################\n";
        $cfg .= "## Time & Date\n";
        $cfg .= "###################################################\n";
        $cfg .= "local_time.ntp_server1 = " . $ntpServer . "\n";
        $cfg .= "local_time.ntp_server2 = europe.pool.ntp.org\n";
        $cfg .= "local_time.time_zone = " . $tzData[0] . "\n";
        $cfg .= "local_time.time_zone_name = " . $tzData[1] . "\n";
        $cfg .= "local_time.summer_time = 2\n";
        $cfg .= "local_time.dst_time_type = 0\n";
        $cfg .= "local_time.time_format = 1\n";
        $cfg .= "local_time.date_format = 3\n";
        $cfg .= "local_time.dhcp_time = 0\n";
        $cfg .= "local_time.manual_ntp_srv_prior = 1\n\n";

        // Taal
        $cfg .= "lang.wui = " . $langWeb . "\n";
        $cfg .= "lang.gui = " . $langLcd . "\n\n";

        // Voice
        $cfg .= "###################################################\n";
        $cfg .= "## Voice\n";
        $cfg .= "###################################################\n";
        $cfg .= "voice.vad = 0\n";
        $cfg .= "voice.cng = 1\n";
        $cfg .= "voice.echo_cancellation = 1\n";
        $cfg .= "voice.jib.adaptive = 1\n";
        $cfg .= "voice.jib.min = 60\n";
        $cfg .= "voice.jib.max = 300\n";
        $cfg .= "voice.jib.normal = 120\n\n";

        // SIP Account
        $cfg .= "###################################################\n";
        $cfg .= "## SIP Account - Line 1\n";
        $cfg .= "###################################################\n";
        $cfg .= "account.1.enable = 1\n";
        $cfg .= "account.1.label = " . $displayName . "\n";
        $cfg .= "account.1.display_name = " . $displayName . "\n";
        $cfg .= "account.1.auth_name = " . $extension . "\n";
        $cfg .= "account.1.user_name = " . $extension . "\n";
        $cfg .= "account.1.password = " . $secret . "\n";
        $cfg .= "account.1.sip_server.1.address = " . $sipServer . "\n";
        $cfg .= "account.1.sip_server.1.port = " . $sipPort . "\n";
        $cfg .= "account.1.sip_server.1.expires = 120\n";
        $cfg .= "account.1.sip_server.1.retry_counts = 3\n";
        $cfg .= "account.1.sip_server.1.failback_mode = 0\n";
        $cfg .= "account.1.outbound_proxy_enable = 0\n";
        $cfg .= "account.1.nat.nat_traversal = 0\n";
        $cfg .= "account.1.nat.udp_update_enable = 1\n";
        $cfg .= "account.1.nat.udp_update_time = 30\n";
        $cfg .= "account.1.dtmf.type = 1\n";
        $cfg .= "account.1.dtmf.dtmf_payload = 101\n";
        $cfg .= "account.1.dtmf.info_type = 1\n";
        $cfg .= "account.1.ptime = 20\n";
        $cfg .= "account.1.srtp_encryption = 0\n";
        $cfg .= "account.1.subscribe_mwi = 1\n";
        $cfg .= "account.1.subscribe_mwi_expires = 900\n";
        $cfg .= "account.1.subscribe_register = 0\n";
        $cfg .= "account.1.unregister_on_reboot = 1\n";
        $cfg .= "account.1.reg_fail_retry_interval = 30\n";
        $cfg .= "account.1.missed_calllog = 1\n";
        $cfg .= "account.1.blf.subscribe_period = 900\n";
        $cfg .= "account.1.dns_cache_type = 1\n";
        $cfg .= "account.1.register_mac = 1\n";
        $cfg .= "account.1.cid_source_ppi = 1\n";
        $cfg .= "account.1.session_timer.enable = 0\n";
        $cfg .= "account.1.check_cseq.enable = 1\n";
        $cfg .= "account.1.check_to_tag.enable = 1\n";
        $cfg .= "account.1.distinctive_ring_tones = 1\n";
        if (!empty($ext['voicemail_enabled'])) {
            $cfg .= "voice_mail.number.1 = *98\n";
        }
        $cfg .= "\n";

        // Codecs
        $cfg .= "###################################################\n";
        $cfg .= "## Codecs\n";
        $cfg .= "###################################################\n";
        $codecMap = [
            'ulaw' => ['0',  'PCMU/8000'],
            'alaw' => ['8',  'PCMA/8000'],
            'g722' => ['9',  'G722/8000'],
            'g729' => ['18', 'G729/8000'],
        ];
        $extCodecs = array_filter(array_map('trim', explode(',', $codecs)));
        $i = 1;
        foreach ($extCodecs as $codec) {
            if (isset($codecMap[$codec])) {
                $cfg .= "account.1.codec." . $i . ".enable = 1\n";
                $cfg .= "account.1.codec." . $i . ".payload_type = " . $codecMap[$codec][0] . "\n";
                $cfg .= "account.1.codec." . $i . ".priority = " . $i . "\n";
                $cfg .= "account.1.codec." . $i . ".rtpmap = " . $codecMap[$codec][1] . "\n";
                $i++;
            }
        }
        for (; $i <= 12; $i++) {
            $cfg .= "account.1.codec." . $i . ".enable = 0\n";
        }
        $cfg .= "\n";

        // Features
        $cfg .= "###################################################\n";
        $cfg .= "## Features\n";
        $cfg .= "###################################################\n";
        $cfg .= "call_waiting.enable = 1\n";
        $cfg .= "call_waiting.tone = 1\n";
        $cfg .= "features.intercom.allow = 1\n";
        $cfg .= "features.intercom.mute = 0\n";
        $cfg .= "features.intercom.tone = 1\n";
        $cfg .= "features.intercom.barge = 0\n";
        $cfg .= "features.dnd_refuse_code = 486\n";
        $cfg .= "features.pickup.blf_visual_enable = 1\n";
        $cfg .= "features.pickup.blf_audio_enable = 1\n";
        $cfg .= "features.save_call_history = 1\n";
        $cfg .= "features.direct_ip_call_enable = 0\n";
        $cfg .= "features.send_key_tone = 1\n";
        $cfg .= "features.dtmf.repetition = 3\n";
        // Remote phonebook (company adresboek)
        $pbGroupId = $phone['phonebook_group_id'] ?? null;
        $baseUrl    = rtrim(Database::getSetting('provision_base_url', ''), '/');
        // Bouw app root op zonder /provision en forceer https
        $appRoot = preg_replace('/\/provision$/', '', $baseUrl);
        $appRoot = preg_replace('/^http:/', 'https:', rtrim($appRoot, '/'));
        if ($pbGroupId && !empty($appRoot)) {
            // Haal groepsnaam op voor menu label
            $pbGroup = Database::fetchOne("SELECT name FROM phonebook_groups WHERE id=?", [$pbGroupId]);
            $pbName  = $pbGroup ? $pbGroup['name'] : 'Company';
            $pbUrl   = $appRoot . '/?page=phonebook&action=xml&group_id=' . $pbGroupId;

            $cfg .= "features.remote_phonebook.enable = 1\n";
            $cfg .= "features.remote_phonebook.flash_time = 21600\n";
            // Positie 1 in het menu - vervangt Directory
            $cfg .= "remote_phonebook.data.1.url = " . $pbUrl . "\n";
            $cfg .= "remote_phonebook.data.1.name = " . $pbName . "\n";
            // Zet als eerste item in Directory menu
            $cfg .= "directory_setting.url = " . $pbUrl . "\n";
            $cfg .= "directory_setting.name = " . $pbName . "\n";
        } else {
            $cfg .= "features.remote_phonebook.enable = 0\n";
        }
        // Softkeys onderste menubalk
        // Idle scherm: History | Adresboek (XML Browser) | DND | Menu
        $cfg .= "phone_setting.idle_soft_key_enable = 1\n";
        if ($pbGroupId && !empty($appRoot)) {
            $cfg .= "softkey.1.id = 28\n";      // History
            $cfg .= "softkey.2.id = 5\n";       // DND
            $cfg .= "softkey.3.id = 30\n";      // Menu
            // Programmable key 2 = XML Browser (type 47) voor adresboek
            $cfg .= "programablekey.2.type = 47\n";
            $cfg .= "programablekey.2.line = 1\n";
            $cfg .= "programablekey.2.label = " . $pbName . "\n";
            $cfg .= "programablekey.2.url = " . $pbUrl . "\n";
        }
        $cfg .= "features.csta_control.enable = 1\n";
        $cfg .= "features.reset_by_long_press_enable = 1\n";
        $cfg .= "features.voice_mail_tone_enable = 1\n";
        $cfg .= "features.power_led_on = 1\n";
        $cfg .= "sip.rfc2543_hold = 0\n";
        $cfg .= "sip.use_out_bound_in_dialog = 1\n";
        $cfg .= "sip.trust_ctrl = 1\n";
        $cfg .= "sip.listen_mode = 0\n";
        $cfg .= "transfer.blind_tran_on_hook_enable = 1\n";
        $cfg .= "transfer.on_hook_trans_enable = 1\n";
        $cfg .= "transfer.semi_attend_tran_enable = 1\n";
        $cfg .= "transfer.dsskey_deal_type = 2\n";
        $cfg .= "transfer.multi_call_trans_enable = 1\n";
        $cfg .= "watch_dog.enable = 1\n";
        $backlightTime = $phone['backlight_time'] ?? 0;
        $cfg .= "phone_setting.active_backlight_level = 7\n";
        $cfg .= "phone_setting.backlight_time = " . $backlightTime . "\n";
        $cfg .= "phone_setting.ring_type = Resource:Ring1.wav\n";
        $cfg .= "phone_setting.hold_reminder.enable = 1\n";
        $cfg .= "phone_setting.miss_call_power_led_flash.enable = 1\n";
        $cfg .= "phone_setting.mail_power_led_flash_enable = 1\n";
        $cfg .= "phone_setting.missed_call_power_led_flash.enable = 1\n";
        $cfg .= "phone_setting.auto_blf_list_enable = 1\n";
        $screensaverTime  = $phone['screensaver_time'] ?? 0;
        $screensaverClock = !empty($phone['screensaver_clock']) ? 1 : 0;
        $cfg .= "screensaver.wait_time = " . $screensaverTime . "\n";
        $cfg .= "screensaver.type = " . ($screensaverTime > 0 ? '1' : '0') . "\n";
        $cfg .= "screensaver.display_clock.enable = " . $screensaverClock . "\n";
        $cfg .= "super_search.recent_call = 1\n";
        $cfg .= "zero_touch.enable = 0\n";
        $cfg .= "auto_redial.enable = 0\n";
        $cfg .= "wui.quick_login = 1\n";
        $cfg .= "network.vlan.internet_port_enable = 0\n";
        $cfg .= "network.lldp.enable = 1\n";
        $cfg .= "network.dhcp_host_name = Yealink-" . $extension . "\n\n";

        // BLF / DSS Keys
        if (!empty($blfKeys)) {
            $cfg .= "###################################################\n";
            $cfg .= "## DSS / BLF Keys\n";
            $cfg .= "###################################################\n";

            $configuredKeys = [];
            foreach ($blfKeys as $key) {
                $configuredKeys[(int)$key['key_number']] = $key;
            }

            $maxKey = max(array_keys($configuredKeys));
            for ($k = 1; $k <= $maxKey; $k++) {
                if (isset($configuredKeys[$k])) {
                    $key    = $configuredKeys[$k];
                    $kType  = self::$keyTypes[$key['key_type']] ?? 16;
                    $label  = $key['label'] ?? ($key['ext_name'] ?? $key['value']);
                    $value  = $key['value'] ?? $key['ext_number'] ?? '';
                    $pickup = $key['pickup_code'] ?? '*8';

                    $cfg .= "linekey." . $k . ".type = " . $kType . "\n";
                    $cfg .= "linekey." . $k . ".label = " . $label . "\n";
                    $cfg .= "linekey." . $k . ".value = " . $value . "\n";
                    $cfg .= "linekey." . $k . ".line = 1\n";
                    if ($key['key_type'] === 'blf') {
                        $cfg .= "linekey." . $k . ".extension = " . $pickup . "\n";
                        $cfg .= "linekey." . $k . ".pickup_value = " . $pickup . "\n";
                    }
                } else {
                    $cfg .= "linekey." . $k . ".type = 0\n";
                }
                $cfg .= "\n";
            }
        }

        return $cfg;
    }

    public static function getMacFilename(string $mac): string
    {
        return strtolower(str_replace([':', '-', ' '], '', $mac)) . '.cfg';
    }

    public static function writeConfigFile(array $phone): bool
    {
        $provPath = Database::getSetting('provision_tftp_path', APP_ROOT . '/provision');
        if (!is_dir($provPath)) {
            @mkdir($provPath, 0755, true);
        }
        $content  = self::generate($phone);
        $filename = $provPath . '/' . self::getMacFilename($phone['mac_address']);
        $result   = file_put_contents($filename, $content);
        if ($result !== false) {
            @chmod($filename, 0644);
            Database::update('provision_phones', [
                'last_provision' => date('Y-m-d H:i:s')
            ], 'id=?', [$phone['id']]);
            return true;
        }
        return false;
    }

    public static function getYealinkModels(): array
    {
        return [
            'T19E2'  => 'T19P E2',
            'T21E2'  => 'T21P E2',
            'T27G'   => 'T27G',
            'T30'    => 'T30',
            'T41S'   => 'T41S',
            'T31G'   => 'T31G',
            'T33G'   => 'T33G',
            'T42U'   => 'T42U',
            'T43U'   => 'T43U',
            'T46U'   => 'T46U (populair)',
            'T48U'   => 'T48U',
            'T53'    => 'T53',
            'T53W'   => 'T53W (WiFi)',
            'T54W'   => 'T54W (WiFi)',
            'T57W'   => 'T57W (WiFi+BT)',
            'T58W'   => 'T58W (Android)',
            'CP920'  => 'CP920 (Conference)',
            'CP960'  => 'CP960 (Conference)',
            'W60B'   => 'W60B (DECT Base)',
            'W70B'   => 'W70B (DECT Base)',
        ];
    }

    public static function getTimezones(): array
    {
        return array_keys(self::$timezoneMap);
    }

    public static function getLanguages(): array
    {
        return [
            'Dutch'    => 'Nederlands',
            'English'  => 'English',
            'German'   => 'Deutsch',
            'French'   => 'Français',
            'Spanish'  => 'Español',
            'Italian'  => 'Italiano',
        ];
    }
}
